import type { Asset, HandoverDraft, Technician, WorkOrder, WorkOrderDraft } from "./types";

export const SEED_ASSETS: Asset[] = [
  { id: "asset-pl3", name: "Packing Line 3", line: "Packaging", status: "down" },
  { id: "asset-pl1", name: "Packing Line 1", line: "Packaging", status: "running" },
  { id: "asset-pl2", name: "Packing Line 2", line: "Packaging", status: "running" },
  { id: "asset-cv-a", name: "Conveyor A (Receiving)", line: "Material Handling", status: "running" },
  { id: "asset-filler-2", name: "Filler Station 2", line: "Processing", status: "degraded" },
  { id: "asset-comp-1", name: "Air Compressor #1", line: "Utilities", status: "running" },
  { id: "asset-label-4", name: "Labeler Unit 4", line: "Packaging", status: "running" },
  { id: "asset-pallet", name: "Palletizer West", line: "Shipping", status: "running" },
];

export const SEED_TECHNICIANS: Technician[] = [
  {
    id: "tech-martinez",
    name: "Frank Martinez",
    shift: "Day",
    years_experience: 31,
    retirement_risk: 95,
    specialty: "Packaging lines, PLC overrides",
  },
  {
    id: "tech-chen",
    name: "Lisa Chen",
    shift: "Swing",
    years_experience: 12,
    retirement_risk: 15,
    specialty: "Conveyors, pneumatics",
  },
  {
    id: "tech-williams",
    name: "Derek Williams",
    shift: "Night",
    years_experience: 8,
    retirement_risk: 10,
    specialty: "Fillers, sensors",
  },
  {
    id: "tech-patel",
    name: "Priya Patel",
    shift: "Night",
    years_experience: 5,
    retirement_risk: 5,
    specialty: "Labelers, vision systems",
  },
  {
    id: "tech-johnson",
    name: "Mike Johnson",
    shift: "Day",
    years_experience: 18,
    retirement_risk: 40,
    specialty: "Compressors, utilities",
  },
];

export const SEED_WORK_ORDERS: WorkOrder[] = [
  {
    id: "wo-2023-0847",
    wo_number: "WO-2023-0847",
    asset_id: "asset-pl3",
    asset_name: "Packing Line 3",
    technician_id: "tech-martinez",
    technician_name: "Frank Martinez",
    date: "2023-03-14T06:22:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "PL3-E04",
    description: "Line 3 dead after changeover. Prox sensor on infeed swapped, relay K17 replaced, no start.",
    technician_notes:
      "NOT IN MANUAL: bypass switch under guard panel east side, label says 'MARTINEZ ONLY'. Flip to MANUAL RUN to bypass prox interlock. Line runs fine. Sensor circuit has intermittent open - schedule replacement but don't hold line for it. Documented here because OEM never added this to the SOP.",
    resolution: "Engaged manual bypass switch on east guard panel. Line restarted in 18 min. Prox sensor scheduled for PM.",
    downtime_minutes: 127,
    is_workaround: 1,
    workaround_label: "East guard panel manual bypass (undocumented)",
  },
  {
    id: "wo-2024-0312",
    wo_number: "WO-2024-0312",
    asset_id: "asset-pl3",
    asset_name: "Packing Line 3",
    technician_id: "tech-martinez",
    technician_name: "Frank Martinez",
    date: "2024-01-22T14:05:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "PL3-E04",
    description: "PL3 won't start post-sanitize. PLC OK, all green. Swapped prox, still dead.",
    technician_notes: "Same as 0847 - east bypass. New guy on swing didn't know about it. Added yellow tag on panel.",
    resolution: "Manual bypass engaged. Line up. Tagged bypass location for training.",
    downtime_minutes: 94,
    is_workaround: 1,
    workaround_label: "East guard panel manual bypass (undocumented)",
  },
  {
    id: "wo-2024-0891",
    wo_number: "WO-2024-0891",
    asset_id: "asset-pl3",
    asset_name: "Packing Line 3",
    technician_id: "tech-williams",
    technician_name: "Derek Williams",
    date: "2024-06-03T23:41:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "PL3-E02",
    description: "Infeed jam cleared but line won't restart. HMI shows 'waiting interlock'.",
    technician_notes: "Checked all E-stops, reset main. Still stuck. Called Frank - he walked me through bypass over radio. Worked first try.",
    resolution: "Used east guard manual bypass per Martinez. Interlock bypassed, line running. Need to add to shift handover docs.",
    downtime_minutes: 45,
    is_workaround: 1,
    workaround_label: "East guard panel manual bypass (undocumented)",
  },
  {
    id: "wo-2025-0044",
    wo_number: "WO-2025-0044",
    asset_id: "asset-pl3",
    asset_name: "Packing Line 3",
    technician_id: "tech-chen",
    technician_name: "Lisa Chen",
    date: "2025-01-08T11:30:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "PL3-E04",
    description: "Prox sensor failure after weekend shutdown. Replaced PNP sensor, verified wiring, PLC input still low.",
    technician_notes: "Standard prox swap didn't fix it. Relay K17 tested good. Issue is interlock logic not sensor itself on this line.",
    resolution: "Replaced prox sensor. Verified 24V at terminal block TB-14. Input still dead - likely cable fault in conduit run. Scheduled cable pull for weekend.",
    downtime_minutes: 210,
    is_workaround: 0,
    workaround_label: null,
  },
  {
    id: "wo-2024-1205",
    wo_number: "WO-2024-1205",
    asset_id: "asset-pl3",
    asset_name: "Packing Line 3",
    technician_id: "tech-martinez",
    technician_name: "Frank Martinez",
    date: "2024-11-18T07:15:00Z",
    type: "preventive",
    status: "closed",
    fault_code: null,
    description: "Quarterly PM on PL3 infeed section.",
    technician_notes: "Cleaned prox lens, checked K17 contacts, verified bypass switch returns to AUTO. All good.",
    resolution: "PM complete. No issues found.",
    downtime_minutes: 45,
    is_workaround: 0,
    workaround_label: null,
  },
  {
    id: "wo-2024-0567",
    wo_number: "WO-2024-0567",
    asset_id: "asset-pl1",
    asset_name: "Packing Line 1",
    technician_id: "tech-chen",
    technician_name: "Lisa Chen",
    date: "2024-04-12T16:20:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "PL1-E11",
    description: "Seal jaw temp fault. Product leaking at seal station.",
    technician_notes: "Heater cartridge reading 40 ohms, should be 28. Replaced HC-442. Also found compressed air leak at actuator - tightened fitting.",
    resolution: "Replaced heater cartridge HC-442. Verified seal temp 340F. Leak fixed.",
    downtime_minutes: 78,
    is_workaround: 0,
    workaround_label: null,
  },
  {
    id: "wo-2023-1102",
    wo_number: "WO-2023-1102",
    asset_id: "asset-pl1",
    asset_name: "Packing Line 1",
    technician_id: "tech-martinez",
    technician_name: "Frank Martinez",
    date: "2023-08-30T09:45:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "PL1-E07",
    description: "Film tracking off after roll change. Product skewed in wrapper.",
    technician_notes: "Don't trust the auto-track on this old Allen-Bradley. Manual adjust pot R-12 on side panel, quarter turn CW usually fixes it.",
    resolution: "Manual tracking adjustment via R-12 pot. Auto-track disabled in PLC bit B3:4/7 per our standard workaround.",
    downtime_minutes: 35,
    is_workaround: 1,
    workaround_label: "Manual film track via R-12 pot (undocumented)",
  },
  {
    id: "wo-2024-0788",
    wo_number: "WO-2024-0788",
    asset_id: "asset-cv-a",
    asset_name: "Conveyor A (Receiving)",
    technician_id: "tech-chen",
    technician_name: "Lisa Chen",
    date: "2024-05-28T22:10:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "CVA-E03",
    description: "Conveyor A stopped mid-shift. VFD showing OC fault.",
    technician_notes: "Checked for jam - clear. Motor amp draw normal when manually rotated. VFD param P-014 was corrupted again after power blip. Reset to 4.2A limit.",
    resolution: "Reset VFD overcurrent parameter P-014 to 4.2A. Conveyor restarted.",
    downtime_minutes: 52,
    is_workaround: 0,
    workaround_label: null,
  },
  {
    id: "wo-2024-0334",
    wo_number: "WO-2024-0334",
    asset_id: "asset-cv-a",
    asset_name: "Conveyor A (Receiving)",
    technician_id: "tech-williams",
    technician_name: "Derek Williams",
    date: "2024-02-14T03:55:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "CVA-E03",
    description: "Same OC fault as before on Conv A. Night shift, no maintenance supervisor.",
    technician_notes: "P-014 keeps resetting after outages. Set to 4.2A per Chen's note in WO-0788. Also found loose terminal on motor junction box T1.",
    resolution: "Tightened T1 terminal, reset P-014. Running.",
    downtime_minutes: 38,
    is_workaround: 0,
    workaround_label: null,
  },
  {
    id: "wo-2025-0118",
    wo_number: "WO-2025-0118",
    asset_id: "asset-filler-2",
    asset_name: "Filler Station 2",
    technician_id: "tech-williams",
    technician_name: "Derek Williams",
    date: "2025-02-01T19:20:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "FL2-E09",
    description: "Fill weight drifting high. Scale alarm every 20 min.",
    technician_notes: "Load cell LC-201 showing 2.3mV offset. Zero cal didn't hold. Swapped LC-201 from spare stock.",
    resolution: "Replaced load cell LC-201. Recalibrated scale. Weights within +/- 0.5g.",
    downtime_minutes: 165,
    is_workaround: 0,
    workaround_label: null,
  },
  {
    id: "wo-2024-0912",
    wo_number: "WO-2024-0912",
    asset_id: "asset-filler-2",
    asset_name: "Filler Station 2",
    technician_id: "tech-williams",
    technician_name: "Derek Williams",
    date: "2024-06-20T08:30:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "FL2-E05",
    description: "Nozzle drip causing product waste. CIP cycle incomplete.",
    technician_notes: "Pinch valve PV-18 diaphragm torn. Used temporary clamp on supply line to isolate until parts arrive - NOT ideal but keeps line at 80% rate.",
    resolution: "Replaced PV-18 diaphragm. CIP verified. Temporary clamp removed.",
    downtime_minutes: 120,
    is_workaround: 1,
    workaround_label: "Supply line clamp for PV-18 drip (temporary)",
  },
  {
    id: "wo-2024-0445",
    wo_number: "WO-2024-0445",
    asset_id: "asset-comp-1",
    asset_name: "Air Compressor #1",
    technician_id: "tech-johnson",
    technician_name: "Mike Johnson",
    date: "2024-03-08T13:00:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "AC1-E02",
    description: "Low plant air pressure. Comp #1 short cycling.",
    technician_notes: "Unload valve stuck. Manual cycle with wrench on stem freed it. Schedule valve kit for next outage.",
    resolution: "Freed stuck unload valve. Pressure stable at 95 PSI.",
    downtime_minutes: 55,
    is_workaround: 0,
    workaround_label: null,
  },
  {
    id: "wo-2023-0623",
    wo_number: "WO-2023-0623",
    asset_id: "asset-comp-1",
    asset_name: "Air Compressor #1",
    technician_id: "tech-johnson",
    technician_name: "Mike Johnson",
    date: "2023-05-19T10:15:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "AC1-E02",
    description: "Compressor short cycling, same symptom as March.",
    technician_notes: "Unload valve again. Johnson trick: tap valve body 3x with rubber mallet before wrench. Works 9/10 times.",
    resolution: "Tapped valve body, cycled manually. Running. Ordered rebuild kit.",
    downtime_minutes: 42,
    is_workaround: 1,
    workaround_label: "Rubber mallet tap on unload valve (undocumented)",
  },
  {
    id: "wo-2024-1023",
    wo_number: "WO-2024-1023",
    asset_id: "asset-label-4",
    asset_name: "Labeler Unit 4",
    technician_id: "tech-patel",
    technician_name: "Priya Patel",
    date: "2024-09-05T21:40:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "LB4-E01",
    description: "Labels skewed 3mm. Vision reject rate spiking.",
    technician_notes: "Peel plate height off after roll change. Set to 2.4mm with feeler gauge, not the HMI auto-cal which drifts.",
    resolution: "Manual peel plate adjustment to 2.4mm. Reject rate back to normal.",
    downtime_minutes: 28,
    is_workaround: 0,
    workaround_label: null,
  },
  {
    id: "wo-2024-0678",
    wo_number: "WO-2024-0678",
    asset_id: "asset-pallet",
    asset_name: "Palletizer West",
    technician_id: "tech-chen",
    technician_name: "Lisa Chen",
    date: "2024-05-10T15:30:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "PLT-E04",
    description: "Palletizer arm fault. HMI fault 4472.",
    technician_notes: "Home position sensor misaligned after forklift hit guard (again). Realigned sensor flag, 1/4 turn on mounting bolt.",
    resolution: "Realigned home position sensor. Fault cleared.",
    downtime_minutes: 67,
    is_workaround: 0,
    workaround_label: null,
  },
  {
    id: "wo-2024-0156",
    wo_number: "WO-2024-0156",
    asset_id: "asset-pl2",
    asset_name: "Packing Line 2",
    technician_id: "tech-martinez",
    technician_name: "Frank Martinez",
    date: "2024-01-30T12:00:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "PL2-E08",
    description: "Case erector jamming every 200 cases. Glue stringing.",
    technician_notes: "Glue temp low because hose heater failed silently. Bypass: run glue pot at max until hose heater replaced. Watch for char.",
    resolution: "Replaced hose heater HH-33. Glue temp stable at 350F.",
    downtime_minutes: 89,
    is_workaround: 1,
    workaround_label: "Max glue pot temp bypass for hose heater failure",
  },
  {
    id: "wo-2025-0067",
    wo_number: "WO-2025-0067",
    asset_id: "asset-pl3",
    asset_name: "Packing Line 3",
    technician_id: "tech-patel",
    technician_name: "Priya Patel",
    date: "2025-01-25T04:10:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "PL3-E01",
    description: "Outfeed accumulation backup. Photo eye PE-33 dirty.",
    technician_notes: "Wiped PE-33 lens. Still false triggering - ambient light from new LED install hitting sensor. Shaded with tape until proper shroud installed.",
    resolution: "Cleaned and shaded PE-33. Accumulation cleared.",
    downtime_minutes: 22,
    is_workaround: 1,
    workaround_label: "Tape shade on PE-33 for LED interference",
  },
  {
    id: "wo-2024-0555",
    wo_number: "WO-2024-0555",
    asset_id: "asset-pl3",
    asset_name: "Packing Line 3",
    technician_id: "tech-williams",
    technician_name: "Derek Williams",
    date: "2024-04-05T01:22:00Z",
    type: "corrective",
    status: "closed",
    fault_code: "PL3-E04",
    description: "Line dead after power bump. All E-stops reset, PLC running.",
    technician_notes: "Relay K17 coil tested OK but contacts pitted. Swapped relay, still no start. This is the prox interlock pattern again.",
    resolution: "Replaced relay K17. Line still wouldn't start - needed bypass per Martinez notes. Used east panel bypass.",
    downtime_minutes: 156,
    is_workaround: 1,
    workaround_label: "East guard panel manual bypass (undocumented)",
  },
];

export const DEMO_FAULT =
  "packing line 3 dead, swapped prox sensor and relay, PLC looks fine, still nothing";

export const CACHED_DIAGNOSIS = {
  asset_id: "asset-pl3",
  asset_name: "Packing Line 3",
  cleaned_fault:
    "Packing Line 3 will not start. Proximity sensor and relay K17 replaced. PLC status normal. Line remains dead.",
  steps: [
    {
      rank: 1,
      action:
        "Locate the manual bypass switch on the east guard panel (labeled 'MARTINEZ ONLY'). Flip to MANUAL RUN to bypass the prox interlock.",
      rationale:
        "Three prior incidents with identical symptoms (dead line after prox/relay swap, PLC OK) were resolved in under 20 minutes using this undocumented bypass. The prox interlock circuit has a known intermittent fault separate from the sensor itself.",
      confidence: "high" as const,
      work_order_id: "wo-2023-0847",
      wo_number: "WO-2023-0847",
      is_workaround: true,
      workaround_label: "East guard panel manual bypass (undocumented)",
    },
    {
      rank: 2,
      action:
        "Verify 24V DC at terminal block TB-14 on the infeed prox input. If present but PLC input stays low, suspect cable fault in conduit run.",
      rationale:
        "WO-2025-0044 documented a prox swap that did not restore the input, pointing to wiring rather than the sensor.",
      confidence: "medium" as const,
      work_order_id: "wo-2025-0044",
      wo_number: "WO-2025-0044",
      is_workaround: false,
    },
    {
      rank: 3,
      action:
        "Inspect relay K17 contacts for pitting even if coil tests good. Replace if contacts show wear.",
      rationale:
        "WO-2024-0555 found pitted K17 contacts; relay swap alone did not restore the line without the bypass.",
      confidence: "medium" as const,
      work_order_id: "wo-2024-0555",
      wo_number: "WO-2024-0555",
      is_workaround: false,
    },
    {
      rank: 4,
      action:
        "After line is running, schedule prox sensor and conduit cable replacement during next planned outage.",
      rationale:
        "Martinez notes in WO-2023-0847 recommend not holding the line for full sensor circuit repair during production.",
      confidence: "high" as const,
      work_order_id: "wo-2023-0847",
      wo_number: "WO-2023-0847",
      is_workaround: false,
    },
  ],
  workarounds: [
    {
      rank: 1,
      action:
        "East guard panel manual bypass switch - bypasses prox interlock, restores line in ~18 min.",
      rationale:
        "Logged by Frank Martinez in WO-2023-0847. Never added to OEM manual or plant SOP. Used successfully in WO-2024-0312, WO-2024-0891, and WO-2024-0555.",
      confidence: "high" as const,
      work_order_id: "wo-2023-0847",
      wo_number: "WO-2023-0847",
      is_workaround: true,
      workaround_label: "East guard panel manual bypass (undocumented)",
    },
  ],
  reasoning_trace: [
    "Parsing fault report: asset match 'packing line 3' -> Packing Line 3 (asset-pl3)",
    "Searching 7 historical work orders for asset-pl3...",
    "Pattern match: 4 incidents with fault code PL3-E04 (line dead, prox/relay swapped, PLC OK)",
    "Ruling out: standard prox replacement (WO-2025-0044 failed with same swap)",
    "Ruling out: relay K17 alone (WO-2024-0555 needed bypass after K17 swap)",
    "Workaround found: east guard panel manual bypass in technician notes (WO-2023-0847)",
    "Knowledge risk: workaround documented only by Frank Martinez (retirement risk 95%)",
    "Assembling ranked plan with 4 steps, 1 undocumented workaround",
  ],
  history_thin: false,
  mode: "cached" as const,
};

export const CACHED_WORK_ORDER: WorkOrderDraft = {
  wo_number: "WO-2025-0142",
  asset_name: "Packing Line 3",
  fault_summary: "Line dead after prox sensor and relay K17 replacement",
  cleaned_description:
    "Packing Line 3 failed to start following prox sensor replacement and relay K17 swap. PLC indicates normal operating status. All E-stops verified reset. Suspected prox interlock circuit fault per historical pattern PL3-E04.",
  priority: "P1 - Production Down",
  recommended_actions: [
    "Engage east guard panel manual bypass (see WO-2023-0847)",
    "Verify 24V at TB-14",
    "Inspect K17 contacts",
    "Schedule conduit cable pull on next outage",
  ],
  estimated_downtime: "15-30 minutes with known workaround",
  parts_needed: ["Prox sensor PNP (spare stock)", "Relay K17 (on hand)"],
};

export const CACHED_HANDOVER: HandoverDraft = {
  shift_summary:
    "Night shift responded to Packing Line 3 down event. Fault matched recurring PL3-E04 pattern. Undocumented bypass from WO-2023-0847 applied to restore production.",
  open_issues: [
    "Prox interlock circuit needs permanent repair - cable fault suspected in conduit run",
    "Bypass switch knowledge still not in official SOP - training gap",
  ],
  completed_today: [
    "Diagnosed PL3 dead-line fault using Shift Sage historical search",
    "Applied east guard panel manual bypass per Martinez workaround",
    "Drafted WO-2025-0142 for CMMS entry",
  ],
  watch_items: [
    "Monitor PL3 infeed prox input on HMI - may drop again mid-run",
    "Frank Martinez retires in 8 months - 4 critical PL3 workarounds depend on his notes",
  ],
  next_shift_priority:
    "Verify line stable through morning production run. Escalate conduit cable repair to reliability team.",
};
